var a = document.getElementById("myAudio1");
var b = document.getElementById("myAudio2");
var c = document.getElementById("myAudio3");
var d = document.getElementById("myAudio4");
var e = document.getElementById("myAudio5");
var f = document.getElementById("myAudio6");
var g = document.getElementById("myAudio7");
var h = document.getElementById("myAudio8");
var i = document.getElementById("myAudio9");
var j = document.getElementById("myAudio10");
var k = document.getElementById("myAudio11");
var l = document.getElementById("myAudio12");
var m = document.getElementById("myAudio13");
var n = document.getElementById("myAudio14");
var o = document.getElementById("myAudio15");
var p = document.getElementById("myAudio16");

function starta() {
    a.play();
    b.pause();
    c.pause();
    d.pause();
    e.pause();
    f.pause();
    g.pause();
    h.pause();
    i.pause();
    j.pause();
    k.pause();
    l.pause();
    m.pause();
    n.pause();
    o.pause();
    p.pause();
    document.getElementById("btnplay2").style.display = 'block';
    document.getElementById("btnplay3").style.display = 'block';
    document.getElementById("btnplay4").style.display = 'block';
    document.getElementById("btnplay5").style.display = 'block';
    document.getElementById("btnplay6").style.display = 'block';
    document.getElementById("btnplay7").style.display = 'block';
    document.getElementById("btnplay8").style.display = 'block';
    document.getElementById("btnplay9").style.display = 'block';
    document.getElementById("btnplay10").style.display = 'block';
    document.getElementById("btnplay11").style.display = 'block';
    document.getElementById("btnplay12").style.display = 'block';
    document.getElementById("btnplay13").style.display = 'block';
    document.getElementById("btnplay14").style.display = 'block';
    document.getElementById("btnplay15").style.display = 'block';
    document.getElementById("btnplay16").style.display = 'block';

    document.getElementById("btnstop2").style.display = 'none';
    document.getElementById("btnstop3").style.display = 'none';
    document.getElementById("btnstop4").style.display = 'none';
    document.getElementById("btnstop5").style.display = 'none';
    document.getElementById("btnstop6").style.display = 'none';
    document.getElementById("btnstop7").style.display = 'none';
    document.getElementById("btnstop8").style.display = 'none';
    document.getElementById("btnstop9").style.display = 'none';
    document.getElementById("btnstop10").style.display = 'none';
    document.getElementById("btnstop11").style.display = 'none';
    document.getElementById("btnstop12").style.display = 'none';
    document.getElementById("btnstop13").style.display = 'none';
    document.getElementById("btnstop14").style.display = 'none';
    document.getElementById("btnstop15").style.display = 'none';
    document.getElementById("btnstop16").style.display = 'none';

    document.getElementById("btnplay1").style.display = 'none';
    document.getElementById("btnstop1").style.display = 'block';
}
function stopa() {
    a.pause();
    b.pause();
    c.pause();
    d.pause();
    e.pause();
    f.pause();
    g.pause();
    h.pause();
    i.pause();
    j.pause();
    k.pause();
    l.pause();
    m.pause();
    n.pause();
    o.pause();
    p.pause();
    document.getElementById("btnplay1").style.display = 'block';
    document.getElementById("btnstop1").style.display = 'none';
}

function startb() {
    document.getElementById("btnplay2").style.display = 'none';
    document.getElementById("btnstop2").style.display = 'block';

    document.getElementById("btnplay1").style.display = 'block';
    document.getElementById("btnplay3").style.display = 'block';
    document.getElementById("btnplay4").style.display = 'block';
    document.getElementById("btnplay5").style.display = 'block';
    document.getElementById("btnplay6").style.display = 'block';
    document.getElementById("btnplay7").style.display = 'block';
    document.getElementById("btnplay8").style.display = 'block';
    document.getElementById("btnplay9").style.display = 'block';
    document.getElementById("btnplay10").style.display = 'block';
    document.getElementById("btnplay11").style.display = 'block';
    document.getElementById("btnplay12").style.display = 'block';
    document.getElementById("btnplay13").style.display = 'block';
    document.getElementById("btnplay14").style.display = 'block';
    document.getElementById("btnplay15").style.display = 'block';
    document.getElementById("btnplay16").style.display = 'block';

    document.getElementById("btnstop1").style.display = 'none';
    document.getElementById("btnstop3").style.display = 'none';
    document.getElementById("btnstop4").style.display = 'none';
    document.getElementById("btnstop5").style.display = 'none';
    document.getElementById("btnstop6").style.display = 'none';
    document.getElementById("btnstop7").style.display = 'none';
    document.getElementById("btnstop8").style.display = 'none';
    document.getElementById("btnstop9").style.display = 'none';
    document.getElementById("btnstop10").style.display = 'none';
    document.getElementById("btnstop11").style.display = 'none';
    document.getElementById("btnstop12").style.display = 'none';
    document.getElementById("btnstop13").style.display = 'none';
    document.getElementById("btnstop14").style.display = 'none';
    document.getElementById("btnstop15").style.display = 'none';
    document.getElementById("btnstop16").style.display = 'none';
    b.play();
    a.pause();
    c.pause();
    d.pause();
    e.pause();
    f.pause();
    g.pause();
    h.pause();
    i.pause();
    j.pause();
    k.pause();
    l.pause();
    m.pause();
    n.pause();
    o.pause();
    p.pause();
}
function stopb() {
    document.getElementById("btnplay2").style.display = 'block';
    document.getElementById("btnstop2").style.display = 'none';
    b.pause();
    a.pause();
    c.pause();
    d.pause();
    e.pause();
    f.pause();
    g.pause();
    h.pause();
    i.pause();
    j.pause();
    k.pause();
    l.pause();
    m.pause();
    n.pause();
    o.pause();
    p.pause();
}

function startc() {
    document.getElementById("btnplay3").style.display = 'none';
    document.getElementById("btnstop3").style.display = 'block';

    document.getElementById("btnplay2").style.display = 'block';
    document.getElementById("btnplay1").style.display = 'block';
    document.getElementById("btnplay4").style.display = 'block';
    document.getElementById("btnplay5").style.display = 'block';
    document.getElementById("btnplay6").style.display = 'block';
    document.getElementById("btnplay7").style.display = 'block';
    document.getElementById("btnplay8").style.display = 'block';
    document.getElementById("btnplay9").style.display = 'block';
    document.getElementById("btnplay10").style.display = 'block';
    document.getElementById("btnplay11").style.display = 'block';
    document.getElementById("btnplay12").style.display = 'block';
    document.getElementById("btnplay13").style.display = 'block';
    document.getElementById("btnplay14").style.display = 'block';
    document.getElementById("btnplay15").style.display = 'block';
    document.getElementById("btnplay16").style.display = 'block';

    document.getElementById("btnstop2").style.display = 'none';
    document.getElementById("btnstop1").style.display = 'none';
    document.getElementById("btnstop4").style.display = 'none';
    document.getElementById("btnstop5").style.display = 'none';
    document.getElementById("btnstop6").style.display = 'none';
    document.getElementById("btnstop7").style.display = 'none';
    document.getElementById("btnstop8").style.display = 'none';
    document.getElementById("btnstop9").style.display = 'none';
    document.getElementById("btnstop10").style.display = 'none';
    document.getElementById("btnstop11").style.display = 'none';
    document.getElementById("btnstop12").style.display = 'none';
    document.getElementById("btnstop13").style.display = 'none';
    document.getElementById("btnstop14").style.display = 'none';
    document.getElementById("btnstop15").style.display = 'none';
    document.getElementById("btnstop16").style.display = 'none';
    c.play();
    a.pause();
    b.pause();
    d.pause();
    e.pause();
    f.pause();
    g.pause();
    h.pause();
    i.pause();
    j.pause();
    k.pause();
    l.pause();
    m.pause();
    n.pause();
    o.pause();
    p.pause();
}
function stopc() {
    document.getElementById("btnplay3").style.display = 'block';
    document.getElementById("btnstop3").style.display = 'none';
    a.pause();
    b.pause();
    c.pause();
    d.pause();
    e.pause();
    f.pause();
    g.pause();
    h.pause();
    i.pause();
    j.pause();
    k.pause();
    l.pause();
    m.pause();
    n.pause();
    o.pause();
    p.pause();
}

function startd() {
    document.getElementById("btnplay2").style.display = 'block';
    document.getElementById("btnplay3").style.display = 'block';
    document.getElementById("btnplay1").style.display = 'block';
    document.getElementById("btnplay5").style.display = 'block';
    document.getElementById("btnplay6").style.display = 'block';
    document.getElementById("btnplay7").style.display = 'block';
    document.getElementById("btnplay8").style.display = 'block';
    document.getElementById("btnplay9").style.display = 'block';
    document.getElementById("btnplay10").style.display = 'block';
    document.getElementById("btnplay11").style.display = 'block';
    document.getElementById("btnplay12").style.display = 'block';
    document.getElementById("btnplay13").style.display = 'block';
    document.getElementById("btnplay14").style.display = 'block';
    document.getElementById("btnplay15").style.display = 'block';
    document.getElementById("btnplay16").style.display = 'block';

    document.getElementById("btnstop2").style.display = 'none';
    document.getElementById("btnstop3").style.display = 'none';
    document.getElementById("btnstop1").style.display = 'none';
    document.getElementById("btnstop5").style.display = 'none';
    document.getElementById("btnstop6").style.display = 'none';
    document.getElementById("btnstop7").style.display = 'none';
    document.getElementById("btnstop8").style.display = 'none';
    document.getElementById("btnstop9").style.display = 'none';
    document.getElementById("btnstop10").style.display = 'none';
    document.getElementById("btnstop11").style.display = 'none';
    document.getElementById("btnstop12").style.display = 'none';
    document.getElementById("btnstop13").style.display = 'none';
    document.getElementById("btnstop14").style.display = 'none';
    document.getElementById("btnstop15").style.display = 'none';
    document.getElementById("btnstop16").style.display = 'none';
    document.getElementById("btnplay4").style.display = 'none';
    document.getElementById("btnstop4").style.display = 'block';
    d.play();
    a.pause();
    b.pause();
    c.pause();
    e.pause();
    f.pause();
    g.pause();
    h.pause();
    i.pause();
    j.pause();
    k.pause();
    l.pause();
    m.pause();
    n.pause();
    o.pause();
    p.pause();
}
function stopd() {
    document.getElementById("btnplay4").style.display = 'block';
    document.getElementById("btnstop4").style.display = 'none';
    a.pause();
    b.pause();
    c.pause();
    d.pause();
    e.pause();
    f.pause();
    g.pause();
    h.pause();
    i.pause();
    j.pause();
    k.pause();
    l.pause();
    m.pause();
    n.pause();
    o.pause();
    p.pause();
}

function starte() {
    document.getElementById("btnplay2").style.display = 'block';
    document.getElementById("btnplay3").style.display = 'block';
    document.getElementById("btnplay4").style.display = 'block';
    document.getElementById("btnplay1").style.display = 'block';
    document.getElementById("btnplay6").style.display = 'block';
    document.getElementById("btnplay7").style.display = 'block';
    document.getElementById("btnplay8").style.display = 'block';
    document.getElementById("btnplay9").style.display = 'block';
    document.getElementById("btnplay10").style.display = 'block';
    document.getElementById("btnplay11").style.display = 'block';
    document.getElementById("btnplay12").style.display = 'block';
    document.getElementById("btnplay13").style.display = 'block';
    document.getElementById("btnplay14").style.display = 'block';
    document.getElementById("btnplay15").style.display = 'block';
    document.getElementById("btnplay16").style.display = 'block';

    document.getElementById("btnstop2").style.display = 'none';
    document.getElementById("btnstop3").style.display = 'none';
    document.getElementById("btnstop4").style.display = 'none';
    document.getElementById("btnstop1").style.display = 'none';
    document.getElementById("btnstop6").style.display = 'none';
    document.getElementById("btnstop7").style.display = 'none';
    document.getElementById("btnstop8").style.display = 'none';
    document.getElementById("btnstop9").style.display = 'none';
    document.getElementById("btnstop10").style.display = 'none';
    document.getElementById("btnstop11").style.display = 'none';
    document.getElementById("btnstop12").style.display = 'none';
    document.getElementById("btnstop13").style.display = 'none';
    document.getElementById("btnstop14").style.display = 'none';
    document.getElementById("btnstop15").style.display = 'none';
    document.getElementById("btnstop16").style.display = 'none';
    document.getElementById("btnplay5").style.display = 'none';
    document.getElementById("btnstop5").style.display = 'block';
    e.play();
    a.pause();
    b.pause();
    c.pause();
    d.pause();
    f.pause();
    g.pause();
    h.pause();
    i.pause();
    j.pause();
    k.pause();
    l.pause();
    m.pause();
    n.pause();
    o.pause();
    p.pause();
}
function stope() {
    document.getElementById("btnplay5").style.display = 'block';
    document.getElementById("btnstop5").style.display = 'none';
    a.pause();
    b.pause();
    c.pause();
    d.pause();
    e.pause();
    f.pause();
    g.pause();
    h.pause();
    i.pause();
    j.pause();
    k.pause();
    l.pause();
    m.pause();
    n.pause();
    o.pause();
    p.pause();
}

function startf() {
    document.getElementById("btnplay2").style.display = 'block';
    document.getElementById("btnplay3").style.display = 'block';
    document.getElementById("btnplay4").style.display = 'block';
    document.getElementById("btnplay5").style.display = 'block';
    document.getElementById("btnplay1").style.display = 'block';
    document.getElementById("btnplay7").style.display = 'block';
    document.getElementById("btnplay8").style.display = 'block';
    document.getElementById("btnplay9").style.display = 'block';
    document.getElementById("btnplay10").style.display = 'block';
    document.getElementById("btnplay11").style.display = 'block';
    document.getElementById("btnplay12").style.display = 'block';
    document.getElementById("btnplay13").style.display = 'block';
    document.getElementById("btnplay14").style.display = 'block';
    document.getElementById("btnplay15").style.display = 'block';
    document.getElementById("btnplay16").style.display = 'block';

    document.getElementById("btnstop2").style.display = 'none';
    document.getElementById("btnstop3").style.display = 'none';
    document.getElementById("btnstop4").style.display = 'none';
    document.getElementById("btnstop5").style.display = 'none';
    document.getElementById("btnstop1").style.display = 'none';
    document.getElementById("btnstop7").style.display = 'none';
    document.getElementById("btnstop8").style.display = 'none';
    document.getElementById("btnstop9").style.display = 'none';
    document.getElementById("btnstop10").style.display = 'none';
    document.getElementById("btnstop11").style.display = 'none';
    document.getElementById("btnstop12").style.display = 'none';
    document.getElementById("btnstop13").style.display = 'none';
    document.getElementById("btnstop14").style.display = 'none';
    document.getElementById("btnstop15").style.display = 'none';
    document.getElementById("btnstop16").style.display = 'none';
    document.getElementById("btnplay6").style.display = 'none';
    document.getElementById("btnstop6").style.display = 'block';
    f.play();
    a.pause();
    b.pause();
    c.pause();
    d.pause();
    e.pause();
    g.pause();
    h.pause();
    i.pause();
    j.pause();
    k.pause();
    l.pause();
    m.pause();
    n.pause();
    o.pause();
    p.pause();
}
function stopf() {
    document.getElementById("btnplay6").style.display = 'block';
    document.getElementById("btnstop6").style.display = 'none';
    a.pause();
    b.pause();
    c.pause();
    d.pause();
    e.pause();
    f.pause();
    g.pause();
    h.pause();
    i.pause();
    j.pause();
    k.pause();
    l.pause();
    m.pause();
    n.pause();
    o.pause();
    p.pause();
}

function startg() {
    document.getElementById("btnplay2").style.display = 'block';
    document.getElementById("btnplay3").style.display = 'block';
    document.getElementById("btnplay4").style.display = 'block';
    document.getElementById("btnplay5").style.display = 'block';
    document.getElementById("btnplay6").style.display = 'block';
    document.getElementById("btnplay1").style.display = 'block';
    document.getElementById("btnplay8").style.display = 'block';
    document.getElementById("btnplay9").style.display = 'block';
    document.getElementById("btnplay10").style.display = 'block';
    document.getElementById("btnplay11").style.display = 'block';
    document.getElementById("btnplay12").style.display = 'block';
    document.getElementById("btnplay13").style.display = 'block';
    document.getElementById("btnplay14").style.display = 'block';
    document.getElementById("btnplay15").style.display = 'block';
    document.getElementById("btnplay16").style.display = 'block';

    document.getElementById("btnstop2").style.display = 'none';
    document.getElementById("btnstop3").style.display = 'none';
    document.getElementById("btnstop4").style.display = 'none';
    document.getElementById("btnstop5").style.display = 'none';
    document.getElementById("btnstop6").style.display = 'none';
    document.getElementById("btnstop1").style.display = 'none';
    document.getElementById("btnstop8").style.display = 'none';
    document.getElementById("btnstop9").style.display = 'none';
    document.getElementById("btnstop10").style.display = 'none';
    document.getElementById("btnstop11").style.display = 'none';
    document.getElementById("btnstop12").style.display = 'none';
    document.getElementById("btnstop13").style.display = 'none';
    document.getElementById("btnstop14").style.display = 'none';
    document.getElementById("btnstop15").style.display = 'none';
    document.getElementById("btnstop16").style.display = 'none';
    document.getElementById("btnplay7").style.display = 'none';
    document.getElementById("btnstop7").style.display = 'block';
    g.play();
    a.pause();
    b.pause();
    c.pause();
    d.pause();
    e.pause();
    f.pause();
    h.pause();
    i.pause();
    j.pause();
    k.pause();
    l.pause();
    m.pause();
    n.pause();
    o.pause();
    p.pause();
}
function stopg() {
    document.getElementById("btnplay7").style.display = 'block';
    document.getElementById("btnstop7").style.display = 'none';
    a.pause();
    b.pause();
    c.pause();
    d.pause();
    e.pause();
    f.pause();
    g.pause();
    h.pause();
    i.pause();
    j.pause();
    k.pause();
    l.pause();
    m.pause();
    n.pause();
    o.pause();
    p.pause();
}

function starth() {
    document.getElementById("btnplay2").style.display = 'block';
    document.getElementById("btnplay3").style.display = 'block';
    document.getElementById("btnplay4").style.display = 'block';
    document.getElementById("btnplay5").style.display = 'block';
    document.getElementById("btnplay6").style.display = 'block';
    document.getElementById("btnplay7").style.display = 'block';
    document.getElementById("btnplay1").style.display = 'block';
    document.getElementById("btnplay9").style.display = 'block';
    document.getElementById("btnplay10").style.display = 'block';
    document.getElementById("btnplay11").style.display = 'block';
    document.getElementById("btnplay12").style.display = 'block';
    document.getElementById("btnplay13").style.display = 'block';
    document.getElementById("btnplay14").style.display = 'block';
    document.getElementById("btnplay15").style.display = 'block';
    document.getElementById("btnplay16").style.display = 'block';

    document.getElementById("btnstop2").style.display = 'none';
    document.getElementById("btnstop3").style.display = 'none';
    document.getElementById("btnstop4").style.display = 'none';
    document.getElementById("btnstop5").style.display = 'none';
    document.getElementById("btnstop6").style.display = 'none';
    document.getElementById("btnstop7").style.display = 'none';
    document.getElementById("btnstop1").style.display = 'none';
    document.getElementById("btnstop9").style.display = 'none';
    document.getElementById("btnstop10").style.display = 'none';
    document.getElementById("btnstop11").style.display = 'none';
    document.getElementById("btnstop12").style.display = 'none';
    document.getElementById("btnstop13").style.display = 'none';
    document.getElementById("btnstop14").style.display = 'none';
    document.getElementById("btnstop15").style.display = 'none';
    document.getElementById("btnstop16").style.display = 'none';
    document.getElementById("btnplay8").style.display = 'none';
    document.getElementById("btnstop8").style.display = 'block';
    h.play();
    a.pause();
    b.pause();
    c.pause();
    d.pause();
    e.pause();
    f.pause();
    g.pause();
    i.pause();
    j.pause();
    k.pause();
    l.pause();
    m.pause();
    n.pause();
    o.pause();
    p.pause();
}
function stoph() {
    document.getElementById("btnplay8").style.display = 'block';
    document.getElementById("btnstop8").style.display = 'none';
    a.pause();
    b.pause();
    c.pause();
    d.pause();
    e.pause();
    f.pause();
    g.pause();
    h.pause();
    i.pause();
    j.pause();
    k.pause();
    l.pause();
    m.pause();
    n.pause();
    o.pause();
    p.pause();
}

function starti() {
    document.getElementById("btnplay2").style.display = 'block';
    document.getElementById("btnplay3").style.display = 'block';
    document.getElementById("btnplay4").style.display = 'block';
    document.getElementById("btnplay5").style.display = 'block';
    document.getElementById("btnplay6").style.display = 'block';
    document.getElementById("btnplay7").style.display = 'block';
    document.getElementById("btnplay8").style.display = 'block';
    document.getElementById("btnplay1").style.display = 'block';
    document.getElementById("btnplay10").style.display = 'block';
    document.getElementById("btnplay11").style.display = 'block';
    document.getElementById("btnplay12").style.display = 'block';
    document.getElementById("btnplay13").style.display = 'block';
    document.getElementById("btnplay14").style.display = 'block';
    document.getElementById("btnplay15").style.display = 'block';
    document.getElementById("btnplay16").style.display = 'block';

    document.getElementById("btnstop2").style.display = 'none';
    document.getElementById("btnstop3").style.display = 'none';
    document.getElementById("btnstop4").style.display = 'none';
    document.getElementById("btnstop5").style.display = 'none';
    document.getElementById("btnstop6").style.display = 'none';
    document.getElementById("btnstop7").style.display = 'none';
    document.getElementById("btnstop8").style.display = 'none';
    document.getElementById("btnstop1").style.display = 'none';
    document.getElementById("btnstop10").style.display = 'none';
    document.getElementById("btnstop11").style.display = 'none';
    document.getElementById("btnstop12").style.display = 'none';
    document.getElementById("btnstop13").style.display = 'none';
    document.getElementById("btnstop14").style.display = 'none';
    document.getElementById("btnstop15").style.display = 'none';
    document.getElementById("btnstop16").style.display = 'none';
    document.getElementById("btnplay9").style.display = 'none';
    document.getElementById("btnstop9").style.display = 'block';
    i.play();
    a.pause();
    b.pause();
    c.pause();
    d.pause();
    e.pause();
    f.pause();
    g.pause();
    h.pause();
    j.pause();
    k.pause();
    l.pause();
    m.pause();
    n.pause();
    o.pause();
    p.pause();
}
function stopi() {
    document.getElementById("btnplay9").style.display = 'block';
    document.getElementById("btnstop9").style.display = 'none';
    a.pause();
    b.pause();
    c.pause();
    d.pause();
    e.pause();
    f.pause();
    g.pause();
    h.pause();
    i.pause();
    j.pause();
    k.pause();
    l.pause();
    m.pause();
    n.pause();
    o.pause();
    p.pause();
}

function startj() {
    document.getElementById("btnplay2").style.display = 'block';
    document.getElementById("btnplay3").style.display = 'block';
    document.getElementById("btnplay4").style.display = 'block';
    document.getElementById("btnplay5").style.display = 'block';
    document.getElementById("btnplay6").style.display = 'block';
    document.getElementById("btnplay7").style.display = 'block';
    document.getElementById("btnplay8").style.display = 'block';
    document.getElementById("btnplay9").style.display = 'block';
    document.getElementById("btnplay1").style.display = 'block';
    document.getElementById("btnplay11").style.display = 'block';
    document.getElementById("btnplay12").style.display = 'block';
    document.getElementById("btnplay13").style.display = 'block';
    document.getElementById("btnplay14").style.display = 'block';
    document.getElementById("btnplay15").style.display = 'block';
    document.getElementById("btnplay16").style.display = 'block';

    document.getElementById("btnstop2").style.display = 'none';
    document.getElementById("btnstop3").style.display = 'none';
    document.getElementById("btnstop4").style.display = 'none';
    document.getElementById("btnstop5").style.display = 'none';
    document.getElementById("btnstop6").style.display = 'none';
    document.getElementById("btnstop7").style.display = 'none';
    document.getElementById("btnstop8").style.display = 'none';
    document.getElementById("btnstop9").style.display = 'none';
    document.getElementById("btnstop1").style.display = 'none';
    document.getElementById("btnstop11").style.display = 'none';
    document.getElementById("btnstop12").style.display = 'none';
    document.getElementById("btnstop13").style.display = 'none';
    document.getElementById("btnstop14").style.display = 'none';
    document.getElementById("btnstop15").style.display = 'none';
    document.getElementById("btnstop16").style.display = 'none';
    document.getElementById("btnplay10").style.display = 'none';
    document.getElementById("btnstop10").style.display = 'block';
    j.play();
    a.pause();
    b.pause();
    c.pause();
    d.pause();
    e.pause();
    f.pause();
    g.pause();
    h.pause();
    i.pause();
    k.pause();
    l.pause();
    m.pause();
    n.pause();
    o.pause();
    p.pause();
}
function stopj() {
    document.getElementById("btnplay10").style.display = 'block';
    document.getElementById("btnstop10").style.display = 'none';
    a.pause();
    b.pause();
    c.pause();
    d.pause();
    e.pause();
    f.pause();
    g.pause();
    h.pause();
    i.pause();
    j.pause();
    k.pause();
    l.pause();
    m.pause();
    n.pause();
    o.pause();
    p.pause();
}

function startk() {
    document.getElementById("btnplay11").style.display = 'none';
    document.getElementById("btnstop11").style.display = 'block';

    document.getElementById("btnplay2").style.display = 'block';
    document.getElementById("btnplay3").style.display = 'block';
    document.getElementById("btnplay4").style.display = 'block';
    document.getElementById("btnplay5").style.display = 'block';
    document.getElementById("btnplay6").style.display = 'block';
    document.getElementById("btnplay7").style.display = 'block';
    document.getElementById("btnplay8").style.display = 'block';
    document.getElementById("btnplay9").style.display = 'block';
    document.getElementById("btnplay10").style.display = 'block';
    document.getElementById("btnplay1").style.display = 'block';
    document.getElementById("btnplay12").style.display = 'block';
    document.getElementById("btnplay13").style.display = 'block';
    document.getElementById("btnplay14").style.display = 'block';
    document.getElementById("btnplay15").style.display = 'block';
    document.getElementById("btnplay16").style.display = 'block';

    document.getElementById("btnstop2").style.display = 'none';
    document.getElementById("btnstop3").style.display = 'none';
    document.getElementById("btnstop4").style.display = 'none';
    document.getElementById("btnstop5").style.display = 'none';
    document.getElementById("btnstop6").style.display = 'none';
    document.getElementById("btnstop7").style.display = 'none';
    document.getElementById("btnstop8").style.display = 'none';
    document.getElementById("btnstop9").style.display = 'none';
    document.getElementById("btnstop10").style.display = 'none';
    document.getElementById("btnstop1").style.display = 'none';
    document.getElementById("btnstop12").style.display = 'none';
    document.getElementById("btnstop13").style.display = 'none';
    document.getElementById("btnstop14").style.display = 'none';
    document.getElementById("btnstop15").style.display = 'none';
    document.getElementById("btnstop16").style.display = 'none';
    k.play();
    a.pause();
    b.pause();
    c.pause();
    d.pause();
    e.pause();
    f.pause();
    g.pause();
    h.pause();
    i.pause();
    j.pause();
    l.pause();
    m.pause();
    n.pause();
    o.pause();
    p.pause();

}
function stopk() {
    document.getElementById("btnplay11").style.display = 'block';
    document.getElementById("btnstop11").style.display = 'none';
    a.pause();
    b.pause();
    c.pause();
    d.pause();
    e.pause();
    f.pause();
    g.pause();
    h.pause();
    i.pause();
    j.pause();
    k.pause();
    l.pause();
    m.pause();
    n.pause();
    o.pause();
    p.pause();
}

function startl() {
    document.getElementById("btnplay12").style.display = 'none';
    document.getElementById("btnstop12").style.display = 'block';
    document.getElementById("btnplay2").style.display='block';
    document.getElementById("btnplay3").style.display='block';
    document.getElementById("btnplay4").style.display='block';
    document.getElementById("btnplay5").style.display='block';
    document.getElementById("btnplay6").style.display='block';
    document.getElementById("btnplay7").style.display='block';
    document.getElementById("btnplay8").style.display='block';
    document.getElementById("btnplay9").style.display='block';
    document.getElementById("btnplay10").style.display='block';
    document.getElementById("btnplay11").style.display='block';
    document.getElementById("btnplay1").style.display='block';
    document.getElementById("btnplay13").style.display='block';
    document.getElementById("btnplay14").style.display='block';
    document.getElementById("btnplay15").style.display='block';
    document.getElementById("btnplay16").style.display='block';

    document.getElementById("btnstop2").style.display='none';
    document.getElementById("btnstop3").style.display='none';
    document.getElementById("btnstop4").style.display='none';
    document.getElementById("btnstop5").style.display='none';
    document.getElementById("btnstop6").style.display='none';
    document.getElementById("btnstop7").style.display='none';
    document.getElementById("btnstop8").style.display='none';
    document.getElementById("btnstop9").style.display='none';
    document.getElementById("btnstop10").style.display='none';
    document.getElementById("btnstop11").style.display='none';
    document.getElementById("btnstop1").style.display='none';
    document.getElementById("btnstop13").style.display='none';
    document.getElementById("btnstop14").style.display='none';
    document.getElementById("btnstop15").style.display='none';
    document.getElementById("btnstop16").style.display='none';
    l.play();
    a.pause();
    b.pause();
    c.pause();
    d.pause();
    e.pause();
    f.pause();
    g.pause();
    h.pause();
    i.pause();
    j.pause();
    k.pause();
    m.pause();
    n.pause();
    o.pause();
    p.pause();
}
function stopl() {
    document.getElementById("btnplay12").style.display = 'block';
    document.getElementById("btnstop12").style.display = 'none';
    a.pause();
    b.pause();
    c.pause();
    d.pause();
    e.pause();
    f.pause();
    g.pause();
    h.pause();
    i.pause();
    j.pause();
    k.pause();
    l.pause();
    m.pause();
    n.pause();
    o.pause();
    p.pause();
}

function startm() {
    document.getElementById("btnplay13").style.display = 'none';
    document.getElementById("btnplay2").style.display='block';
    document.getElementById("btnplay3").style.display='block';
    document.getElementById("btnplay4").style.display='block';
    document.getElementById("btnplay5").style.display='block';
    document.getElementById("btnplay6").style.display='block';
    document.getElementById("btnplay7").style.display='block';
    document.getElementById("btnplay8").style.display='block';
    document.getElementById("btnplay9").style.display='block';
    document.getElementById("btnplay10").style.display='block';
    document.getElementById("btnplay11").style.display='block';
    document.getElementById("btnplay12").style.display='block';
    document.getElementById("btnplay1").style.display='block';
    document.getElementById("btnplay14").style.display='block';
    document.getElementById("btnplay15").style.display='block';
    document.getElementById("btnplay16").style.display='block';

    document.getElementById("btnstop2").style.display='none';
    document.getElementById("btnstop3").style.display='none';
    document.getElementById("btnstop4").style.display='none';
    document.getElementById("btnstop5").style.display='none';
    document.getElementById("btnstop6").style.display='none';
    document.getElementById("btnstop7").style.display='none';
    document.getElementById("btnstop8").style.display='none';
    document.getElementById("btnstop9").style.display='none';
    document.getElementById("btnstop10").style.display='none';
    document.getElementById("btnstop11").style.display='none';
    document.getElementById("btnstop12").style.display='none';
    document.getElementById("btnstop1").style.display='none';
    document.getElementById("btnstop14").style.display='none';
    document.getElementById("btnstop15").style.display='none';
    document.getElementById("btnstop16").style.display='none';
    document.getElementById("btnstop13").style.display = 'block';
    m.play();
    a.pause();
    b.pause();
    c.pause();
    d.pause();
    e.pause();
    f.pause();
    g.pause();
    h.pause();
    i.pause();
    j.pause();
    k.pause();
    l.pause();
    n.pause();
    o.pause();
    p.pause();
}
function stopm() {
    document.getElementById("btnplay13").style.display = 'block';
    document.getElementById("btnstop13").style.display = 'none';
    a.pause();
    b.pause();
    c.pause();
    d.pause();
    e.pause();
    f.pause();
    g.pause();
    h.pause();
    i.pause();
    j.pause();
    k.pause();
    l.pause();
    m.pause();
    n.pause();
    o.pause();
    p.pause();
}

function startn() {
    document.getElementById("btnplay2").style.display='block';
    document.getElementById("btnplay3").style.display='block';
    document.getElementById("btnplay4").style.display='block';
    document.getElementById("btnplay5").style.display='block';
    document.getElementById("btnplay6").style.display='block';
    document.getElementById("btnplay7").style.display='block';
    document.getElementById("btnplay8").style.display='block';
    document.getElementById("btnplay9").style.display='block';
    document.getElementById("btnplay10").style.display='block';
    document.getElementById("btnplay11").style.display='block';
    document.getElementById("btnplay12").style.display='block';
    document.getElementById("btnplay13").style.display='block';
    document.getElementById("btnplay1").style.display='block';
    document.getElementById("btnplay15").style.display='block';
    document.getElementById("btnplay16").style.display='block';

    document.getElementById("btnstop2").style.display='none';
    document.getElementById("btnstop3").style.display='none';
    document.getElementById("btnstop4").style.display='none';
    document.getElementById("btnstop5").style.display='none';
    document.getElementById("btnstop6").style.display='none';
    document.getElementById("btnstop7").style.display='none';
    document.getElementById("btnstop8").style.display='none';
    document.getElementById("btnstop9").style.display='none';
    document.getElementById("btnstop10").style.display='none';
    document.getElementById("btnstop11").style.display='none';
    document.getElementById("btnstop12").style.display='none';
    document.getElementById("btnstop13").style.display='none';
    document.getElementById("btnstop1").style.display='none';
    document.getElementById("btnstop15").style.display='none';
    document.getElementById("btnstop16").style.display='none';
    document.getElementById("btnplay14").style.display = 'none';
    document.getElementById("btnstop14").style.display = 'block';
    n.play();
    a.pause();
    b.pause();
    c.pause();
    d.pause();
    e.pause();
    f.pause();
    g.pause();
    h.pause();
    i.pause();
    j.pause();
    k.pause();
    l.pause();
    m.pause();
    o.pause();
    p.pause();
}
function stopn() {
    document.getElementById("btnplay14").style.display = 'block';
    document.getElementById("btnstop14").style.display = 'none';
    a.pause();
    b.pause();
    c.pause();
    d.pause();
    e.pause();
    f.pause();
    g.pause();
    h.pause();
    i.pause();
    j.pause();
    k.pause();
    l.pause();
    m.pause();
    n.pause();
    o.pause();
    p.pause();
}

function starto() {
    document.getElementById("btnplay2").style.display='block';
    document.getElementById("btnplay3").style.display='block';
    document.getElementById("btnplay4").style.display='block';
    document.getElementById("btnplay5").style.display='block';
    document.getElementById("btnplay6").style.display='block';
    document.getElementById("btnplay7").style.display='block';
    document.getElementById("btnplay8").style.display='block';
    document.getElementById("btnplay9").style.display='block';
    document.getElementById("btnplay10").style.display='block';
    document.getElementById("btnplay11").style.display='block';
    document.getElementById("btnplay12").style.display='block';
    document.getElementById("btnplay13").style.display='block';
    document.getElementById("btnplay14").style.display='block';
    document.getElementById("btnplay1").style.display='block';
    document.getElementById("btnplay16").style.display='block';

    document.getElementById("btnstop2").style.display='none';
    document.getElementById("btnstop3").style.display='none';
    document.getElementById("btnstop4").style.display='none';
    document.getElementById("btnstop5").style.display='none';
    document.getElementById("btnstop6").style.display='none';
    document.getElementById("btnstop7").style.display='none';
    document.getElementById("btnstop8").style.display='none';
    document.getElementById("btnstop9").style.display='none';
    document.getElementById("btnstop10").style.display='none';
    document.getElementById("btnstop11").style.display='none';
    document.getElementById("btnstop12").style.display='none';
    document.getElementById("btnstop13").style.display='none';
    document.getElementById("btnstop14").style.display='none';
    document.getElementById("btnstop15").style.display='none';
    document.getElementById("btnstop16").style.display='none';
    document.getElementById("btnplay15").style.display = 'none';
    document.getElementById("btnstop15").style.display = 'block';
    o.play();
    a.pause();
    b.pause();
    c.pause();
    d.pause();
    e.pause();
    f.pause();
    g.pause();
    h.pause();
    i.pause();
    j.pause();
    k.pause();
    l.pause();
    m.pause();
    n.pause();
    p.pause();
}
function stopo() {
    document.getElementById("btnplay15").style.display = 'block';
    document.getElementById("btnstop15").style.display = 'none';
    a.pause();
    b.pause();
    c.pause();
    d.pause();
    e.pause();
    f.pause();
    g.pause();
    h.pause();
    i.pause();
    j.pause();
    k.pause();
    l.pause();
    m.pause();
    n.pause();
    o.pause();
    p.pause();
}

function startp() {
    document.getElementById("btnplay2").style.display='block';
    document.getElementById("btnplay3").style.display='block';
    document.getElementById("btnplay4").style.display='block';
    document.getElementById("btnplay5").style.display='block';
    document.getElementById("btnplay6").style.display='block';
    document.getElementById("btnplay7").style.display='block';
    document.getElementById("btnplay8").style.display='block';
    document.getElementById("btnplay9").style.display='block';
    document.getElementById("btnplay10").style.display='block';
    document.getElementById("btnplay11").style.display='block';
    document.getElementById("btnplay12").style.display='block';
    document.getElementById("btnplay13").style.display='block';
    document.getElementById("btnplay14").style.display='block';
    document.getElementById("btnplay15").style.display='block';
    document.getElementById("btnplay1").style.display='block';

    document.getElementById("btnstop2").style.display='none';
    document.getElementById("btnstop3").style.display='none';
    document.getElementById("btnstop4").style.display='none';
    document.getElementById("btnstop5").style.display='none';
    document.getElementById("btnstop6").style.display='none';
    document.getElementById("btnstop7").style.display='none';
    document.getElementById("btnstop8").style.display='none';
    document.getElementById("btnstop9").style.display='none';
    document.getElementById("btnstop10").style.display='none';
    document.getElementById("btnstop11").style.display='none';
    document.getElementById("btnstop12").style.display='none';
    document.getElementById("btnstop13").style.display='none';
    document.getElementById("btnstop14").style.display='none';
    document.getElementById("btnstop15").style.display='none';
    document.getElementById("btnstop16").style.display='none';
    document.getElementById("btnplay16").style.display = 'none';
    document.getElementById("btnstop16").style.display = 'block';
    p.play();
    a.pause();
    b.pause();
    c.pause();
    d.pause();
    e.pause();
    f.pause();
    g.pause();
    h.pause();
    i.pause();
    j.pause();
    k.pause();
    l.pause();
    m.pause();
    n.pause();
    o.pause();
}
function stopp() {
    document.getElementById("btnplay16").style.display = 'block';
    document.getElementById("btnstop16").style.display = 'none';
    a.pause();
    b.pause();
    c.pause();
    d.pause();
    e.pause();
    f.pause();
    g.pause();
    h.pause();
    i.pause();
    j.pause();
    k.pause();
    l.pause();
    m.pause();
    n.pause();
    o.pause();
    p.pause();
}